### ISSUE TITLE
2.4 Changes

### ISSUE THREAD

**Issue by ccbrown** [ccbrown/xiv-sim#36]
Needs the 2.4 balance changes:

http://na.finalfantasyxiv.com/lodestone/topics/detail/4a7a48cd010551b65b1e0f03b318d0d45bf52d59#battle

**Comment by jingai** [comment]
No, but seems 38eafd5584c5e25932fdc6fbddcd594476100b67 addressed it.

However, DRG DPS still seems low relatively.

**Comment by jingai** [comment]
Found the issues with DRG.  Fixing/testing now.

**Comment by ccbrown** [comment]
https://github.com/ccbrown/xiv-sim/commit/fbdfc469da8f43b0228992787513f8e2e9d41153
