### ISSUE TITLE
Animation lock duration should be added for each skill

### ISSUE THREAD

**Issue by kernelthree** [ccbrown/xiv-sim#54]
It looks like the animation lock is set to 1s globally:

```
void Actor::triggerAnimationLock() {
	_animationLockEndTime = _time + 1_s;
}
```

This prevents double off-GCD weaving for Bard, which is possible without delaying their next GCD since buffs have a shorter animation lock. I think the animation lock timer should be added per skill, as there are some skills (e.g. X-Potion of Dexterity) that take longer to use than others.

**Comment by jingai** [comment]
Is there any way to determine with any real accuracy what the animation lock is for each skill, since the game doesn't explicitly say anywhere?

**Comment by kernelthree** [comment]
The best way I can currently think of is to use ACT, use a whole bunch of skills simultaneously and then check the ACT encounter logs for times:

```
[20:13:47.413] 15:1011E2E0:Ibu Profen:6E:Bloodletter:400008E8:Striking Dummy:0:0:0:0:0:0:0:0:70205:223:0:0:0:0:0:0:2778:2778:0:0:1000:1000:-137.0108:-80.94916:12:269:6035:1687:132:1000:1000:-123.3018:-75.98682:12
[20:13:47.413] 15:1011E2E0:Ibu Profen:08:Shot:400008E8:Striking Dummy:0:0:0:0:0:0:0:0:70205:14D:0:0:0:0:0:0:2778:2778:0:0:1000:1000:-137.0108:-80.94916:12:269:6035:1687:132:1000:1000:-123.3018:-75.98682:12
[20:13:48.248] 15:1011E2E0:Ibu Profen:62:Straight Shot:400008E8:Striking Dummy:A12:82:1D:62:0:0:0:0:70203:163:0:0:0:0:0:0:2445:2778:0:0:1000:1000:-137.0108:-80.94916:12:269:6035:1687:132:1000:1000:-127.8737:-77.87978:12
```

In this case I queued Straight Shot directly after Bloodletter, so Bloodletter's animation lock is roughly 0.835 seconds long.

**Comment by jingai** [comment]
Yup, that'd work.  Unfortunately I play on PS4 though so I'd be unable to assist with collecting the times.

But that'd be a good start for anyone that plays on PC and wants to see this happen:  collect the times and get them into a google spreadsheet or something.

**Comment by Eroleice** [comment]
I just made some test

for most weapon skills and ability

weapon skill has a 1.000 second animation lock time;
ability (buff) has 0.650 second animation lock time;
ability (dmg) has different animation lock time and i'm gonna do more test and put result in a google document.

jingai if you can add a animation time to each skill that would be nice (when update the model for Heavensward), i'll do the statistic.

PS: I'm waiting for the early access

**Comment by jingai** [comment]
I'll certainly help as I find time.  Excited to play though too, this weekend :)

**Comment by ccbrown** [comment]
This is actually really trivial. Just knocked it out:

https://github.com/ccbrown/xiv-sim/commit/d743f1eef60df99d9af4dbe2bf4707803a2cd7e7

So for each action, you can now add an override:

```
virtual std::chrono::microseconds animationLock() const override { return 800_ms; }
```
