### ISSUE TITLE
Are you going to keep working for Heavensward?

### ISSUE THREAD

**Issue by Eroleice** [ccbrown/xiv-sim#57]
The rotation and damage formula will change a lot, are you going to keep updating it?

I would like to help if you don't mind. I play all jobs and currently finished FCoB as all 10 jobs. And I also did lot of work on dmg statistic. I notice you're using the formula from <http://valk.dancing-mad.com>.
That's a good formula but when players get higher status, the formula is not accurate as it was. I did a lot of calculation and research, here's my damage formula for bard:

(Weapon Damage * (0.00366 * DEX + 0.26) + 0.0745 * DEX + 4.95) * ((Determination - 202) * 0.0005 + 1.00) * 1.26 * (potency/100)

I'm planing to continue my studying on this, if you're interested let me know plz. <3

**Comment by ccbrown** [comment]
I'll gladly keep maintaining and updating this, but I've cancelled my subscription and don't currently have any plans to reactivate it.

So yeah, I'll do what I can with your help, but unfortunately I personally won't be making attempts at verifying the accuracy of your formulas.

Thanks!

**Comment by Eroleice** [comment]
Err, here's another problem I met, maybe it's a stupid problem.

I tried to intall this simulator on a Ubuntu 12.04 server. I tried it many times since half years ago but i never succeed. I always stack on the step "CXX=c++ LLVM_CONFIG=llvm-config-3.4 make". Here's the error message I got:

root@ffxiv-simulate:~/xiv-sim# CXX=c++ LLVM_CONFIG=llvm-config-3.4 make
c++ -g -Wall -O3 -std=c++1y `llvm-config-3.4 --cppflags` -c src/Action.cpp -o obj/Action.o -MD -MT 'obj/Action.o' -MF 'obj/Action.d'
/bin/bash: c++: command not found
make: *** [obj/Action.o] Error 127

I did some search on google and install GCC and tried some other ways, but none of them works.

I'm new to Ubuntu actually, I would so appreciate if you can give me some help <3

**Comment by jingai** [comment]
/usr/bin/c++ is a symlink to /etc/alternatives/c++ on Debian, which is in turn a symlink to /usr/bin/g++.

Not sure why it's not linked on your system, but just change "CXX=c++" to "CXX=g++" to get it going.

**Comment by jingai** [comment]
FWIW, I intend to keep helping with this project as well.  Just waiting for Heavensward to see what changes.

**Comment by Eroleice** [comment]
Finally I do make some progress Q.Q   Here's what I got, if someone meet the same problem and find this post:

I checked my gcc version by "gcc --version" and it says 4.6.4, no good, we need a newer version. I use this post to get a 4.9 version gcc: http://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-4-9-on-ubuntu-14-04

Then when I build the simulator, it shows an error message with "http://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-4-9-on-ubuntu-14-04"

And I use this bug fix: http://reviews.llvm.org/rL201729  The first file is located "/usr/lib/llvm-3.4/lib/clang/3.4/include" on my server, and I don't find the second file but it still works.

Now I built the simulator, but when I test it, it shows:

======================================================
root@ffxiv-simulate:~/xiv-sim# time ./simulator single-json --length 660 subjects/monk-bis.conf rotations/monk-bis.sl
Unable to read configuration.

real	0m0.008s
user	0m0.000s
sys	0m0.005s
======================================================

I'm currently on that.....   (＠・ˍ・)

**Comment by jingai** [comment]
./simulator single-json --length 660 **id** subjects/monk-bis.conf rotations/monk-bis.sl

You're missing the **id** argument.

**Comment by Eroleice** [comment]
;3; You're my god jingai, i'm so excited to see that result!

btw i'm running ./simulator thorough-json subjects/monk-bis.conf rotations/monk-bis.sl 360 660 id

i guess it will take a long time? xD

I hope my server won't crash.

**Comment by jingai** [comment]
Glad to be of help :)

**Comment by ccbrown** [comment]
Yep they tend to take 3-10 minutes on my machine.

Went ahead and fixed that readme example. :P
