### ISSUE TITLE
>3< change on NIN rotation (right before 3.0)

### ISSUE THREAD

**Issue by Eroleice** [ccbrown/xiv-sim#58]
I asked my friends come to see how this simulator work. She gives me this advice for NIN rotation (5 min after she saw the code!):

>line 17 : 3.0 --> 8.0
>line 39 : 4.0 --> 2.0
>line 45: 2.0 --> 1.0

And I got a 620 dps with the new rotation :3

I know it's two days before 3.0 but I just want to show some slight change can make big improvement.

**Comment by jingai** [comment]
I don't see the same gain here.  I see a drop, actually.

Remember that when you're comparing rotations, you need to either use the same seed and duration, or run thorough sims (also with the same durations).

**Comment by Eroleice** [comment]
Strenge, I put my rotation code one the website but it doesn't even work, but it works perfectly on my local website. Here's the full code:

```
if (!AuraCount(self, "kiss-damage-buff", self))
	use "kiss-of-the-wasp";

if (GlobalCooldownRemaining(self) > 0.5) {
	if (IsReady(self, "huton") and AuraTimeRemaining(self, "skill-speed-up", self) < 5.0)
		use "huton";

	if (TP(self) <= 600 and IsReady(self, "invigorate"))
		use "invigorate";

	if (IsReady(self, "blood-for-blood"))
		use "blood-for-blood";

	if (IsReady(self, "internal-release"))
		use "internal-release";

	if (CooldownRemaining(self, "trick-attack") < 8.0 and IsReady(self, "suiton"))
		use "suiton";

	if (IsReady(self, "raiton") and AuraTimeRemaining(self, "skill-speed-up", self) > 17.0 and CooldownRemaining(self, "trick-attack") > 17.0)
		use "raiton";

	if (IsReady(self, "trick-attack"))
		use "trick-attack";

	if (AuraTimeRemaining(target, "trick-attack-debuff", self) and IsReady(self, "kassatsu"))
		use "kassatsu";

	if (IsReady(self, "raiton-crit"))
		use "raiton-crit";
}

if (AuraTimeRemaining(target, "shadow-fang-dot", self) < 4.0 and IsReady(self, "shadow-fang-combo"))
	use "shadow-fang-combo";

if (IsReady(self, "gust-slash-combo"))
	use "gust-slash-combo";

if (AuraTimeRemaining(target, "dancing-edge", self) < 2.0 and IsReady(self, "dancing-edge-combo"))
	use "dancing-edge-combo";

if (IsReady(self, "aeolian-edge-combo"))
	use "aeolian-edge-combo";

if (AuraTimeRemaining(target, "mutilate-dot", self) < 1.0)
	use "mutilate";

if (GlobalCooldownRemaining(self) > 0.5) {
	if (IsReady(self, "mug"))
		use "mug";

	if (IsReady(self, "jugulate"))
		use "jugulate";
}

use "spinning-edge";
```

**Comment by jingai** [comment]
At 240 seconds with a seed of 12180102631677857000, I get 574 DPS with your rotation vs 576 DPS with the one that's already there.

Remember that duration and seed matter.. a lot.

**Comment by Eroleice** [comment]
wait, is the rotation on <http://sim.ffxivguild.net/?sim&preset=ninja-bis> out of date?

**Comment by jingai** [comment]
Hmm, it appears it is.

**Comment by Eroleice** [comment]
lol I see. That's a sad news for my friend, she thought she're so pro to make such an improvement.

btw when I do the big scale simulate, the result always be incomplet. It shows the max dps, see, min dps, seed and some of the effects and dmg, but it stops there, so I can't get the whole dmg result, and the server can't do any more simulate unless I reboot it. It's ok for me since I can reboot, but that would be nice if I don't have to. <3

![Image of Screenshot](http://i.imgur.com/kifGENB.png)

**Comment by jingai** [comment]
It isn't incomplete, it's just not yet finished.  I don't know what hardware you're on, but it takes about 10-15 min on my i7-4770k.
